number_of_clusters: 5
ir_weight: 0.6
temp_weight: 0.4
input_paths:
  era5: data/ERA5_daily.nc
output_paths:
  models: results/models
  plots: results/plots
  cluster_outputs: results/cluster_outputs
  summaries: results/summaries
